# Generated by Django 5.2.13 on 2026-05-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_submissions',
            field=models.JSONField(default=dict),
        ),
    ]
